'use server';

/**
 * @fileOverview This file defines a Genkit flow for summarizing validation data and generating reports.
 * It uses a tool-calling approach to allow the AI to either provide a text summary or
 * create a structured report based on the user's query.
 *
 * - summarizeValidationData - A function that summarizes validation data.
 * - SummarizeValidationDataInput - The input type for the summarizeValidationData function.
 * - SummarizeValidationDataOutput - The return type for the summarizeValidationData function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'zod';

const ValidationDataSchema = z.object({
  ideaId: z.string().describe('Unique identifier for the idea submission.'),
  validationScore: z.number().describe('Overall validation score for the idea.'),
  keyInsights: z.array(z.string()).describe('Key insights or findings from the validation process.'),
});

export type ValidationData = z.infer<typeof ValidationDataSchema>;

const SummarizeValidationDataInputSchema = z.object({
  validationData: z.array(ValidationDataSchema).describe('Array of validation data objects to summarize.'),
  query: z.string().describe('User query, e.g. "identify trends" or "create a CSV of approved ideas"'),
});
export type SummarizeValidationDataInput = z.infer<typeof SummarizeValidationDataInputSchema>;


const GeneratedReportSchema = z.object({
  id: z.string().describe('A unique ID for the generated report, e.g., REP-AI-001.'),
  name: z.string().describe('A descriptive name for the report, e.g., "Approved Ideas (AI Generated)".'),
  type: z.enum(['CSV', 'PDF']).describe('The format of the generated report.'),
  date: z.string().describe('The date the report was generated, in YYYY-MM-DD format.'),
  status: z.enum(['Ready', 'Generating']).describe('The status of the report.'),
});
export type GeneratedReport = z.infer<typeof GeneratedReportSchema>;

const SummarizeValidationDataOutputSchema = z.object({
  summary: z.string().describe('A summary of the validation data, highlighting promising ideas and trends, or a confirmation message if a report was generated.'),
  generatedReport: GeneratedReportSchema.optional().describe('The details of a structured report if one was generated by the tool.'),
});
export type SummarizeValidationDataOutput = z.infer<typeof SummarizeValidationDataOutputSchema>;


// The Tool that the AI can decide to call
const createStructuredReport = ai.defineTool(
  {
    name: 'createStructuredReport',
    description: 'Use this tool when the user explicitly asks to create or generate a structured report (like a CSV or PDF).',
    inputSchema: z.object({
      reportName: z.string().describe("A descriptive name for the report based on the user's query."),
      format: z.enum(['CSV', 'PDF']).describe("The format for the report, inferred from the user's query."),
    }),
    outputSchema: GeneratedReportSchema,
  },
  async (input) => {
    console.log(`AI tool called: createStructuredReport with name "${input.reportName}" and format ${input.format}`);
    // In a real app, this would trigger a background job to generate the file.
    // For now, we just return the metadata for the report.
    return {
      id: `REP-AI-${Date.now().toString().slice(-5)}`,
      name: input.reportName,
      type: input.format,
      date: new Date().toISOString().split('T')[0],
      status: 'Ready',
    };
  }
);


const summarizeValidationDataPrompt = ai.definePrompt({
  name: 'summarizeValidationDataPrompt',
  input: {
    schema: SummarizeValidationDataInputSchema,
  },
  output: {
    schema: SummarizeValidationDataOutputSchema,
  },
  tools: [createStructuredReport],
  prompt: `You are an AI assistant helping a college principal admin to identify promising ideas and trends from a set of idea submissions and their validation data.

Your primary goal is to answer the user's query.

- If the user asks a general question or asks for a summary, provide a concise text summary in the 'summary' field.
- If the user explicitly asks you to "create", "generate", or "make" a report (e.g., "generate a CSV of all ideas"), you MUST use the 'createStructuredReport' tool.
- When you use the tool, also provide a brief confirmation message in the 'summary' field, for example: "I have generated the CSV report for you."

Analyze the provided data to answer the user's query.

Validation Data: {{{json validationData}}}

Query: {{{query}}}
`,
});

export async function summarizeValidationData(
  input: SummarizeValidationDataInput
): Promise<SummarizeValidationDataOutput> {
  const llmResponse = await summarizeValidationDataPrompt(input);
  
  if (!llmResponse.output) {
    throw new Error('The AI did not return a valid response.');
  }

  // Check if the tool was called and handle the output
  if (llmResponse.output.generatedReport) {
    return {
      summary: llmResponse.output.summary || "Report generated successfully.",
      generatedReport: llmResponse.output.generatedReport,
    };
  }
  
  return {
    summary: llmResponse.output.summary,
    generatedReport: undefined,
  };
}
