
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function TermsOfServicePage() {
    return (
        <Card>
            <CardHeader>
                <CardTitle>Terms of Service</CardTitle>
                <p className="text-sm text-muted-foreground">Last updated: September 3, 2025</p>
            </CardHeader>
            <CardContent className="space-y-6">
                <section>
                    <h2>1. Acceptance of Terms</h2>
                    <p>By accessing or using the PragatiAI platform, you agree to be bound by these Terms of Service and our Privacy Policy. If you do not agree to these terms, please do not use our services.</p>
                </section>
                <section>
                    <h2>2. Description of Service</h2>
                    <p>PragatiAI provides an AI-powered platform for educational institutions and individuals to manage, validate, and nurture innovative ideas. The service includes AI-based feedback, role-based dashboards, and analytics.</p>
                </section>
                 <section>
                    <h2>3. User Accounts & Startup India Alignment</h2>
                    <p>You are responsible for maintaining the confidentiality of your account. Our platform encourages innovation in line with the Startup India initiative, but we are not an official government entity. You agree to provide accurate information during registration.</p>
                </section>
                <section>
                    <h2>4. Intellectual Property</h2>
                    <p>You retain ownership of the intellectual property rights in the ideas and content you submit. By submitting an idea, you grant PragatiAI a non-exclusive, worldwide, royalty-free license to use, process, and display your content solely for the purpose of providing services to you and your affiliated institution.</p>
                </section>
                <section>
                    <h2>5. Limitation of Liability</h2>
                    <p>PragatiAI provides its services "as is." The feedback and analysis generated by our AI are for informational purposes only and should not be considered professional legal, financial, or business advice. We are not liable for any decisions made based on the information provided by our platform.</p>
                </section>
                 <section>
                    <h2>6. Governing Law</h2>
                    <p>These Terms shall be governed by and construed in accordance with the laws of India, without regard to its conflict of law provisions. All disputes are subject to the exclusive jurisdiction of the courts in India.</p>
                </section>
            </CardContent>
        </Card>
    )
}
